src/Entity/IrregularVerb.php
<?php

namespace App\Entity;

use App\Repository\IrregularVerbRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IrregularVerbRepository::class)]
class IrregularVerb
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text', nullable: true)]
    private $nl_infinitive;

    #[ORM\Column(type: 'text', nullable: true)]
    private $nl_simple_past_singular;

    #[ORM\Column(type: 'text', nullable: true)]
    private $nl_simple_past_plural;

    #[ORM\Column(type: 'text', nullable: true)]
    private $nl_past_participle;

    #[ORM\Column(type: 'text', nullable: true)]
    private $en_infinitive;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNlInfinitive(): ?string
    {
        return $this->nl_infinitive;
    }

    public function setNlInfinitive(?string $nl_infinitive): self
    {
        $this->nl_infinitive = $nl_infinitive;

        return $this;
    }

    public function getNlSimplePastSingular(): ?string
    {
        return $this->nl_simple_past_singular;
    }

    public function setNlSimplePastSingular(?string $nl_simple_past_singular): self
    {
        $this->nl_simple_past_singular = $nl_simple_past_singular;

        return $this;
    }

    public function getNlSimplePastPlural(): ?string
    {
        return $this->nl_simple_past_plural;
    }

    public function setNlSimplePastPlural(?string $nl_simple_past_plural): self
    {
        $this->nl_simple_past_plural = $nl_simple_past_plural;

        return $this;
    }

    public function getNlPastParticiple(): ?string
    {
        return $this->nl_past_participle;
    }

    public function setNlPastParticiple(?string $nl_past_participle): self
    {
        $this->nl_past_participle = $nl_past_participle;

        return $this;
    }

    public function getEnInfinitive(): ?string
    {
        return $this->en_infinitive;
    }

    public function setEnInfinitive(?string $en_infinitive): self
    {
        $this->en_infinitive = $en_infinitive;

        return $this;
    }
}

src/Controller/IrregularVerbController.php
<?php

namespace App\Controller;

use App\Repository\IrregularVerbRepository;
use App\Serializer\IrregularVerbSerializer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IrregularVerbController extends AbstractController
{
    /**
     * @Route("/verb/{id}", name="verb")
     */
    public function showOne(int $id, IrregularVerbRepository $irregularVerbRepository): Response
    {
        $irregularVerb = $irregularVerbRepository->find($id);

        if (!$irregularVerb) {
            throw $this->createNotFoundException(
                'No irregular verb found for id '.$id
            );
        }

        return $this->render('ShowOneVerb.html.twig', [
            'irregular_verb' => $irregularVerb,
            'conjugated_verb' => IrregularVerbSerializer::conjugate($irregularVerb),
        ]);
    }

    /**
     * @Route("/irregular-verbs", name="irregular-verbs")
     */
    public function showAll( IrregularVerbRepository $irregularVerbRepository): Response
    {
        $irregularVerbs = $irregularVerbRepository->findAll();

        return $this->render('ShowAllVerbs.html.twig', [
            'irregular_verbs' => IrregularVerbSerializer::serializeAll($irregularVerbs),
        ]);
    }
}

templates/ShowAllVerbs.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Onregelmatige werkwoorden{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <style>
        table, th, td {
            border:1px solid black;
        }
    </style>
    <body>
        <h2>Onregelmatige werkwoorden</h2>

        <table style="width:50%">
            <tr>
                <th></th>
                <th>Infinitief</th>
                <th>Imperfectum enkelvoud</th>
                <th>Imperfectum meervoud</th>
                <th>Perfectum</th>
                <th>Engels</th>
            </tr>
                {% for irregular_verb in irregular_verbs %}
                    <tr>
                        <td>
                            <a href="/verb/{{ irregular_verb.id }}">{{ irregular_verb.id }}</a>
                        </td>
                        <td>{{ irregular_verb.nlInfinitive }}</td>
                        <td>{{ irregular_verb.nlSimplePastSingular }}</td>
                        <td>{{ irregular_verb.nlSimplePastPlural }}</td>
                        <td>{{ irregular_verb.nlPastParticiple }}</td>
                        <td>{{ irregular_verb.enInfinitive }}</td>
                    </tr>
                {% endfor %}
        </table>
    </body>
</html>

templates/ShowOneVerb.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{{ irregular_verb.nlInfinitive }}{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <script src="https://verbix-api.nyc3.cdn.digitaloceanspaces.com/conjugator/v2.0.2.js"></script>
        <style>
            .pronoun { color: green; }
            .irregular { color: red; }
            .orto { color: blue; }
            .arca { color: purple; }
            .obsolete { color: gray; }
        </style>
    </head>
    <style>
        table, th, td {
            border:1px solid black;
        }
    </style>
    <body>
        <h2>{{ irregular_verb.nlInfinitive }}</h2>

        <table style="width:25%">
            <tr>
                <th scope="col">Infinitief</th>
                <td>{{ irregular_verb.nlInfinitive }}</td>
            </tr>
            <tr>
                <th scope="col">Imperfectum enkelvoud</th>
                <td>{{ irregular_verb.nlSimplePastSingular }}</td>
            </tr>
            <tr>
                <th scope="col">Imperfectum meervoud</th>
                <td>{{ irregular_verb.nlSimplePastPlural }}</td>
            </tr>
            <tr>
                <th scope="col">Perfectum</th>
                <td>{{ irregular_verb.nlPastParticiple }}</td>
            </tr>
            <tr>
                <th scope="col">Engels</th>
                <td>{{ irregular_verb.enInfinitive }}</td>
            </tr>
        </table>

        <h3>Present tense conjugation</h3>
        {% for form in conjugated_verb %}
            <tr>
                <li>
                    {{ form }}
                </li>
            </tr>
        {% endfor %}

    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>